version: "3"

services:
  web:
    build: $PWD/docker/web # Specifying the file to build
    image: webapi # Image name
    container_name: web-container # Container name
    ports: # Port on the left to access,right side is the port inside the container
      - "3000:3000"
    environment: # Container internal environment variable
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=mysecretpassword1234"
    links:
      - db
    # volumes:
    #   - "$PWD/docker/web/app:/app" #共有フォルダの設定
    stdin_open: true
    tty: true

  db:
    image: postgres:10.6-alpine # Base image file
    container_name: db-container # Container name
    ports: # Port on the left to access,right side is the port inside the container
      - "5432:5432" 
    environment: # Container internal environment variable
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword1234"
    volumes: 
      - $PWD/docker/db/init:/docker-entrypoint-initdb.d # Initial data create
      - dbdata:/var/lib/postgresql/data # mount postgresql volume

volumes:
  dbdata:
    driver_opts:
      type: none
      device: $PWD/.dbdata # Create volume for postgresql
      o: bind